# Site settings
title: Maximiliano Canellas
author: 
email: me@maxidevops.com  # Add your email or remove if not needed
description: A personal page for sharing professional information and technical insights.
baseurl: "" # Empty for user/organization pages (e.g., username.github.io)
url: "https://maxidev.github.io" # Your GitHub Pages URL
lang: en # Primary language for the site

# Remote Theme
remote_theme: "jekyll/minima@v2.5.1"

# Minima theme settings
minima:
  date_format: "%b %-d, %Y" # e.g. Nov 3, 2023
  social_links:
    github: maxidev # your GitHub username
    linkedin: maxicanellas # your LinkedIn username

# SEO settings
# twitter:
#   username: # your Twitter handle (without @)
#   card: summary_large_image

# Social media profiles
# social:
#   name: Maximiliano Canellas
#   links:
#     - https://linkedin.com/in/maxicanellas
#     - https://github.com/maxidev
#     - https://keybase.io/maxidev

# Plugins (required for remote theme)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap # Automatically generates a sitemap.xml
  - jekyll-readme-index # Enables using README.md as index

# Build settings
markdown: kramdown
permalink: pretty

# Use README.md as the home page
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor